env: local

database:
    db_address: localhost:5432
    db_user: user
    db_pass: 123
    db_name: auth

http_server:
    address: localhost:3001
    timeout: 5s
    idle_timeout: 60s

grpc_server:
    address: localhost:50051

casbin:
    config_path: .\rbac\config.yaml

redis:
    address: localhost:6379
    db_pass: 123
    db: 0
    proto: 2